"""Book table field update

Revision ID: fffce1ec0836
Revises: 1b6fd894ac2b
Create Date: 2024-07-28 22:17:53.385476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fffce1ec0836'
down_revision: Union[str, None] = '1b6fd894ac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('books', sa.Column('year_published', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('summary', sa.Text(), nullable=False))
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.drop_column('books', 'published_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_column('books', 'summary')
    op.drop_column('books', 'year_published')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
